/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller.vista;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taller.modelo.*;

/**
 *
 * @author User
 */
public class BusquedaAparatosView extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;

    /**
     * Creates new form BusquedaAparatosView
     */
    public BusquedaAparatosView() {
        initComponents();
        modelo = new DefaultTableModel();
        ArmaCabeceraDeTabla();
        CargaComboCliente();
        cbCliente.setSelectedIndex(-1);
        CargaComboServicio();
        cbServicio.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbBuscar = new javax.swing.JComboBox<>();
        cbCliente = new javax.swing.JComboBox<>();
        cbServicio = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAparato = new javax.swing.JTable();
        txFecha = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Búsqueda de Aparatos");

        jLabel2.setText("Buscar por:");

        jLabel3.setText("Dueño:");

        jLabel4.setText("Servicio:");

        jLabel5.setText("Fecha de Ingreso:");

        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dueño", "Servicio Aplicado", "Fecha de Ingreso" }));
        cbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarActionPerformed(evt);
            }
        });

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        cbServicio.setEnabled(false);
        cbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServicioActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tAparato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo de Aparato", "Nro. de Serie", "Fecha de Ingreso"
            }
        ));
        jScrollPane1.setViewportView(tAparato);

        txFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBuscar, 0, 280, Short.MAX_VALUE)
                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaComboCliente(){
        try {
            Conexion con = new Conexion();
            ClienteData cd = new ClienteData(con);
            ArrayList<Cliente> listaCliente = (ArrayList) cd.obtenerListaDeClientes();
            
            for (Cliente cliente : listaCliente) {
                cbCliente.addItem(cliente);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CargaComboServicio(){
        try {
            Conexion con = new Conexion();
            ServicioData sd = new ServicioData(con);
            ArrayList<Servicio> listaServicio = (ArrayList) sd.obtenerListaDeServicios();
            
            for (Servicio servicio : listaServicio) {
                cbServicio.addItem(servicio);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void ArmaCabeceraDeTabla(){
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Id");
        columnas.add("Tipo de Aparato");
        columnas.add("Nro. de Serie");
        columnas.add("Fecha de Ingreso");
        
        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }
        tAparato.setModel(modelo);
        
    }
    
    private void BorrarFilasTabla(){
        int a = tAparato.getRowCount() -1;
        for(int i=a; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    public void CargaDatosTabla(ArrayList<Aparato> listaAparatos){
        BorrarFilasTabla();
        
        for (Aparato ap : listaAparatos) {
            modelo.addRow(new Object[]{ap.getIdAparato(), ap.getTipoAparato(), ap.getNroSerie(), ap.getfIngreso()});
        }
    }
    
    private void BloqueaControles(){
        cbCliente.setEnabled(false);
        cbCliente.setSelectedIndex(-1);
        cbServicio.setEnabled(false);
        cbServicio.setSelectedIndex(-1);
        txFecha.setEnabled(false);
        btnBuscar.setEnabled(false);
    }
    
    private LocalDate ConvierteFecha(String fecha){
        DateTimeFormatter formaFecha = DateTimeFormatter.ofPattern("d/MM/yyyy");
        return LocalDate.parse(fecha, formaFecha);
    }
    
    private void cbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarActionPerformed
        int seleccion = cbBuscar.getSelectedIndex();
        BloqueaControles();
        BorrarFilasTabla();
        switch(seleccion){
            case 0:
                cbCliente.setEnabled(true);
                cbCliente.setSelectedIndex(-1);
                break;
            case 1: 
                cbServicio.setEnabled(true);
                cbServicio.setSelectedIndex(-1);
                break;
            case 2:
                txFecha.setEnabled(true);
                btnBuscar.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_cbBuscarActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        try {
            BorrarFilasTabla();
            if (cbCliente.getSelectedIndex() > -1) {
                Cliente cliente = (Cliente) cbCliente.getSelectedItem();
                Conexion con = new Conexion();
                AparatoData ad = new AparatoData(con);
                ArrayList<Aparato> listaAparatos = (ArrayList) ad.obtenerAparatosXDuenio(cliente.getIdCliente());
            
                CargaDatosTabla(listaAparatos);
            }            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cbClienteActionPerformed

    private void cbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServicioActionPerformed
        try {
            BorrarFilasTabla();
            if (cbServicio.getSelectedIndex() > -1) {
                Servicio serv = (Servicio) cbServicio.getSelectedItem();
                Conexion con = new Conexion();
                AparatoData ad = new AparatoData(con);
                ArrayList<Aparato> listaAparatos = (ArrayList) ad.obtenerAparatosXServicio(serv.getIdServicio());
            
                CargaDatosTabla(listaAparatos);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cbServicioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            BorrarFilasTabla();
            if (txFecha.getText() != null) {
                Conexion con = new Conexion();
                LocalDate fIngreso = ConvierteFecha(txFecha.getText());
                AparatoData ad = new AparatoData(con);
                ArrayList<Aparato> listaAparatos = (ArrayList) ad.obtenerAparatosXFecha(fIngreso);
            
                CargaDatosTabla(listaAparatos);
            }
            else{
                JOptionPane.showMessageDialog(null, "Debe ingresar una fecha para buscar por fecha");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbBuscar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<Servicio> cbServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tAparato;
    private javax.swing.JTextField txFecha;
    // End of variables declaration//GEN-END:variables
}
