/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller.vista;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import taller.modelo.Aparato;
import taller.modelo.AparatoData;
import taller.modelo.Cliente;
import taller.modelo.ClienteData;
import taller.modelo.Conexion;
import taller.modelo.Reparacion;
import taller.modelo.ReparacionData;
import taller.modelo.Servicio;
import taller.modelo.ServicioData;

/**
 *
 * @author User
 */
public class BusquedaAparatoView extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    /**
     * Creates new form BusquedaAparatoView
     */
    public BusquedaAparatoView() {
        initComponents();
        modelo = new DefaultTableModel();
        ArmaCabeceraTabla();
        CargaComboClientes();
        cbCliente.setSelectedIndex(-1);
        CargarComboServicios();
        cbServicio.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbServicio = new javax.swing.JComboBox<>();
        dtFIngreso = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAparato = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Búsqueda de Aparatos");

        jLabel2.setText("Dueño:");

        jLabel3.setText("Servicio:");

        jLabel4.setText("Fecha Ingreso:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tAparato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo Aparato", "Nro. Serie", "Fecha Ingreso"
            }
        ));
        jScrollPane2.setViewportView(tAparato);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtFIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnBuscar)
                        .addGap(64, 64, 64)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dtFIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaComboClientes(){
        try {
            Conexion con = new Conexion();
            ClienteData cd = new ClienteData(con);
            ArrayList<Cliente> listaClientes = (ArrayList) cd.obtenerListaDeClientes();
            
            for (Cliente cliente : listaClientes) {
                cbCliente.addItem(cliente);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReparacionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CargarComboServicios(){
        try {
            Conexion con = new Conexion();
            ServicioData sd = new ServicioData(con);
            ArrayList<Servicio> listaServicios = (ArrayList) sd.obtenerListaDeServicios();
            
            for (Servicio servicio : listaServicios) {
                cbServicio.addItem(servicio);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReparacionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private LocalDate ConvierteFecha(java.util.Date fecha){
        if (fecha == null) {
            return null;
        } else {
            return fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
    }
    
    private void ArmaCabeceraTabla(){
        ArrayList <Object> columnas = new ArrayList<>();
        columnas.add("Id");
        columnas.add("Tipo Aparato");
        columnas.add("Nro. Serie");
        columnas.add("Fecha Ingreso");
        
        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }
    }
    
    private void CargaTabla (ArrayList<Aparato> lista){
        BorraFilasTabla();
        
        for (Aparato aparato : lista) {
            modelo.addRow(new Object[] {aparato.getIdAparato(), aparato.getTipoAparato(), aparato.getNroSerie(), aparato.getfIngreso()});
        }
        tAparato.setModel(modelo);
    }
    
    private void BorraFilasTabla(){
        int a = modelo.getRowCount() -1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
            
        }
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cbCliente.setSelectedIndex(-1);
        cbServicio.setSelectedIndex(-1);
        dtFIngreso.setDate(null);
        BorraFilasTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            LocalDate ingreso = ConvierteFecha(dtFIngreso.getDate());
            Conexion con = new Conexion();
            AparatoData ad = new AparatoData(con);
            ArrayList<Aparato> listaAparato = (ArrayList) ad.obtenerListaDeAparatos();
            
            if (cbCliente.getSelectedIndex() > -1){
                Cliente cliente = (Cliente) cbCliente.getSelectedItem(); 
                listaAparato.removeIf(a -> a.getDuenio().getIdCliente() != cliente.getIdCliente());
            }
            if (cbServicio.getSelectedIndex() > -1) {
                Servicio servicio = (Servicio) cbServicio.getSelectedItem();
                ReparacionData rd = new ReparacionData(con);
                ArrayList<Reparacion> listaRep = (ArrayList) rd.obtenerListaDeReparacion();
                listaRep.removeIf(rep -> rep.getServicio().getIdServicio() != servicio.getIdServicio());
                //listaAparato.removeIf(ap -> ap.get)
            }
            if (ingreso != null) {
                listaAparato.removeIf(ap -> !ap.getfIngreso().isEqual(ingreso));
            }
            
            CargaTabla(listaAparato);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaAparatoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<Servicio> cbServicio;
    private com.toedter.calendar.JDateChooser dtFIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tAparato;
    // End of variables declaration//GEN-END:variables
}
